---
name: PShop
main: AlexItz16\Shop\Shop
version: 0.0.5
api:
- 3.0.0
- 4.0.0
author: sLeeD
depend:
- PointAPI
- FormAPI
commands:
  pshop:
    description: Open Tokens Shop
    aliases: [tkshop]
permissions:
  tokenshop:
    default: true
    description: Allows use of the /ps command
...
